import type { Dimension, Cluster, Preset } from '../../../shared/schema';

export const DIMENSIONS: Dimension[] = [
  {
    id: 'openheid',
    label: 'Openheid',
    description: 'Mate van nieuwsgierigheid, abstract denken en bereidheid tot nieuwe ervaringen.',
    scaleType: 'continuous',
    min: 0,
    max: 100,
    minLabel: 'Vertrouwd & praktisch',
    maxLabel: 'Nieuwsgierig & experimenteel',
    defaultValue: 50,
    confidenceLevel: 'high',
    source: 'Big Five persoonlijkheidsmodel (Costa & McCrae, 1992)',
    cultureSensitive: false,
    axisGroup: 'personality',
  },
  {
    id: 'consciëntieusheid',
    label: 'Consciëntieusheid',
    description: 'Mate van ordelijkheid, zelfdiscipline, doelgerichtheid en organisatievermogen.',
    scaleType: 'continuous',
    min: 0,
    max: 100,
    minLabel: 'Flexibel & spontaan',
    maxLabel: 'Gestructureerd & doelgericht',
    defaultValue: 50,
    confidenceLevel: 'high',
    source: 'Big Five persoonlijkheidsmodel',
    cultureSensitive: false,
    axisGroup: 'personality',
  },
  {
    id: 'introversie',
    label: 'Introversie – Extraversie',
    description: 'Hoe je energie haalt: uit stilte en diepte (introversie) of uit sociale interactie en stimulatie (extraversie).',
    scaleType: 'continuous',
    min: 0,
    max: 100,
    minLabel: 'Sterk introvert',
    maxLabel: 'Sterk extravert',
    defaultValue: 50,
    confidenceLevel: 'high',
    source: 'Big Five / MBTI onderzoeksbasis',
    cultureSensitive: true,
    axisGroup: 'personality',
  },
  {
    id: 'normgerichtheid',
    label: 'Normgerichtheid',
    description: 'Mate waarin je waarde hecht aan maatschappelijke conventies, regels en verwachtingen van anderen.',
    scaleType: 'continuous',
    min: 0,
    max: 100,
    minLabel: 'Autonoom & afwijkend',
    maxLabel: 'Sterk normconform',
    defaultValue: 60,
    confidenceLevel: 'medium',
    source: 'Modellering op basis van sociaalpsychologisch onderzoek (Cialdini, 1993)',
    cultureSensitive: true,
    axisGroup: 'social',
  },
  {
    id: 'routinebehoefte',
    label: 'Routinebehoefte',
    description: 'Hoe sterk je voorkeur is voor voorspelbaarheid, vaste patronen en structuur in je dagelijks leven.',
    scaleType: 'continuous',
    min: 0,
    max: 100,
    minLabel: 'Open voor chaos',
    maxLabel: 'Sterke voorkeur voor routine',
    defaultValue: 55,
    confidenceLevel: 'medium',
    source: 'Zachte schatting; gerelateerd aan neuroticisme en sensorische verwerking',
    cultureSensitive: false,
    axisGroup: 'social',
  },
  {
    id: 'prikkelgevoeligheid',
    label: 'Prikkelgevoeligheid',
    description: 'Hoe intensief je sensorische prikkels en sociale input ervaart. Hoog = snel overprikkeld; laag = hunkert naar meer stimulatie.',
    scaleType: 'continuous',
    min: 0,
    max: 100,
    minLabel: 'Lage gevoeligheid (prikkelzoekend)',
    maxLabel: 'Hoge gevoeligheid (snel overprikkeld)',
    defaultValue: 45,
    confidenceLevel: 'medium',
    source: 'Sensory Processing Sensitivity (Aron, 1996); HSP-onderzoek',
    cultureSensitive: false,
    axisGroup: 'neurotype',
  },
  {
    id: 'aandachtsregulatie',
    label: 'Aandachtsregulatie',
    description: 'Hoe makkelijk je focus vasthoud, schakelt of juist in hyper-focus terechtkomt. Lager = moeilijker reguleren.',
    scaleType: 'continuous',
    min: 0,
    max: 100,
    minLabel: 'Moeilijk te reguleren (ADHD-profiel)',
    maxLabel: 'Sterke, stabiele focus',
    defaultValue: 60,
    confidenceLevel: 'medium',
    source: 'DSM-5 ADHD-criteria; zachte schatting voor continuüm',
    cultureSensitive: false,
    axisGroup: 'neurotype',
  },
  {
    id: 'systeemdenken',
    label: 'Systeemdenken & Abstractie',
    description: 'Voorkeur voor abstract, patroongericht en systemisch denken ten opzichte van concreet, praktisch denken.',
    scaleType: 'continuous',
    min: 0,
    max: 100,
    minLabel: 'Concreet & praktisch',
    maxLabel: 'Abstract & systemisch',
    defaultValue: 50,
    confidenceLevel: 'medium',
    source: 'Gerelateerd aan IQ-subfactoren en cognitieve stijl (CHC-model)',
    cultureSensitive: false,
    axisGroup: 'cognitive',
  },
];

export const CLUSTERS: Cluster[] = [
  {
    id: 'mainstream',
    name: 'Mainstream Midden',
    description: 'De statistische kern van de mensheid: sociaal aanpasbaar, matig open, behoefte aan enige routine en structuur.',
    center: { openheid: 50, consciëntieusheid: 55, introversie: 52, normgerichtheid: 65, routinebehoefte: 58, prikkelgevoeligheid: 45, aandachtsregulatie: 62, systeemdenken: 48 },
    radius: 0.45,
    prevalence: 0.45,
    color: '#4f98a3',
    family: 'mainstream',
    warning: 'Dit is het statistisch meest frequente profiel, niet een morele norm.',
  },
  {
    id: 'analytisch-open',
    name: 'Analytisch & Open',
    description: 'Hoge openheid, sterk systeemdenken, minder normgericht. Typisch voor academici, techneuten en onderzoekers.',
    center: { openheid: 80, consciëntieusheid: 65, introversie: 35, normgerichtheid: 35, routinebehoefte: 40, prikkelgevoeligheid: 55, aandachtsregulatie: 58, systeemdenken: 85 },
    radius: 0.18,
    prevalence: 0.12,
    color: '#7a39bb',
    family: 'analytical',
    warning: 'Vereenvoudigde cluster op basis van gecombineerde eigenschappen.',
  },
  {
    id: 'creatief-autonoom',
    name: 'Creatief & Autonoom',
    description: 'Hoge openheid, lage normgerichtheid, weinig routinebehoefte. Typisch voor kunstenaars, ontwerpers en ondernemers.',
    center: { openheid: 85, consciëntieusheid: 35, introversie: 45, normgerichtheid: 25, routinebehoefte: 25, prikkelgevoeligheid: 65, aandachtsregulatie: 45, systeemdenken: 60 },
    radius: 0.14,
    prevalence: 0.08,
    color: '#da7101',
    family: 'creative',
    warning: 'Cluster op basis van zachte schattingen.',
  },
  {
    id: 'neurodivergent-gevoelig',
    name: 'Neurodivergent & Prikkelgevoelig',
    description: 'Hoge prikkelgevoeligheid, moeilijkere aandachtsregulatie, sterk systeemdenken. Overlapt met HSP/ADHD/autisme-profielen.',
    center: { openheid: 70, consciëntieusheid: 45, introversie: 30, normgerichtheid: 30, routinebehoefte: 70, prikkelgevoeligheid: 85, aandachtsregulatie: 32, systeemdenken: 75 },
    radius: 0.16,
    prevalence: 0.15,
    color: '#a12c7b',
    family: 'neurodivergent',
    warning: 'Geen diagnose. Cluster dekt een breed, divers spectrum. Raadpleeg een professional voor klinische beoordeling.',
  },
  {
    id: 'sociaal-normgericht',
    name: 'Sociaal & Normgericht',
    description: 'Sterke extraversie, hoge normgerichtheid, weinig behoefte aan afwijking. Gedijt in sociale structuren.',
    center: { openheid: 40, consciëntieusheid: 60, introversie: 80, normgerichtheid: 82, routinebehoefte: 60, prikkelgevoeligheid: 35, aandachtsregulatie: 65, systeemdenken: 38 },
    radius: 0.20,
    prevalence: 0.18,
    color: '#437a22',
    family: 'social',
    warning: 'Cultureel sterk beïnvloed: normgerichtheid varieert per samenleving.',
  },
  {
    id: 'autonoom-introvert',
    name: 'Autonoom & Introvert',
    description: 'Laag normconform, sterk introvert, behoefte aan autonomie. Typisch voor solistische denkers en onderzoekers.',
    center: { openheid: 65, consciëntieusheid: 58, introversie: 22, normgerichtheid: 20, routinebehoefte: 48, prikkelgevoeligheid: 60, aandachtsregulatie: 55, systeemdenken: 72 },
    radius: 0.13,
    prevalence: 0.09,
    color: '#006494',
    family: 'autonomous',
    warning: 'Zachte schatting op basis van persoonlijkheidsonderzoek.',
  },
];

export const PRESETS: Preset[] = [
  {
    id: 'mediaan',
    name: 'Mediane Mens',
    description: 'Het statistische middelpunt van alle dimensies.',
    values: { openheid: 50, consciëntieusheid: 55, introversie: 52, normgerichtheid: 60, routinebehoefte: 55, prikkelgevoeligheid: 45, aandachtsregulatie: 60, systeemdenken: 50 },
    note: 'Dit is geen ideaal — dit is het statistische gemiddelde.',
  },
  {
    id: 'analytisch',
    name: 'Analytische Specialist',
    description: 'Hoog in openheid en systeemdenken, introvert, laag normgericht.',
    values: { openheid: 82, consciëntieusheid: 70, introversie: 28, normgerichtheid: 30, routinebehoefte: 42, prikkelgevoeligheid: 55, aandachtsregulatie: 60, systeemdenken: 88 },
    note: 'Didactisch composiet — geen echte persoon.',
  },
  {
    id: 'creatief',
    name: 'Creatieve Generalist',
    description: 'Hoge openheid, lage routine en normgerichtheid, breed geïnteresseerd.',
    values: { openheid: 88, consciëntieusheid: 32, introversie: 50, normgerichtheid: 22, routinebehoefte: 20, prikkelgevoeligheid: 68, aandachtsregulatie: 42, systeemdenken: 62 },
    note: 'Didactisch composiet — geen echte persoon.',
  },
  {
    id: 'neurodivergent',
    name: 'Neurodivergent Profiel',
    description: 'Hoge prikkelgevoeligheid, moeilijkere aandachtsregulatie, sterk systeemdenken.',
    values: { openheid: 72, consciëntieusheid: 42, introversie: 28, normgerichtheid: 28, routinebehoefte: 72, prikkelgevoeligheid: 88, aandachtsregulatie: 28, systeemdenken: 78 },
    note: 'Geen diagnose. Illustratief composiet.',
  },
  {
    id: 'normgericht',
    name: 'Sterk Normgericht',
    description: 'Hoge normgerichtheid, extravert, stabiele routine.',
    values: { openheid: 38, consciëntieusheid: 65, introversie: 78, normgerichtheid: 85, routinebehoefte: 65, prikkelgevoeligheid: 32, aandachtsregulatie: 68, systeemdenken: 38 },
    note: 'Didactisch composiet — geen moreel oordeel.',
  },
  {
    id: 'autonoom',
    name: 'Hoge Autonomie',
    description: 'Laag normconform, introvert, hoge openheid.',
    values: { openheid: 70, consciëntieusheid: 55, introversie: 20, normgerichtheid: 18, routinebehoefte: 45, prikkelgevoeligheid: 62, aandachtsregulatie: 55, systeemdenken: 75 },
    note: 'Didactisch composiet.',
  },
  {
    id: 'routinegericht',
    name: 'Sterk Routinegericht',
    description: 'Hoge behoefte aan structuur en voorspelbaarheid.',
    values: { openheid: 30, consciëntieusheid: 78, introversie: 50, normgerichtheid: 68, routinebehoefte: 88, prikkelgevoeligheid: 55, aandachtsregulatie: 72, systeemdenken: 42 },
    note: 'Didactisch composiet.',
  },
  {
    id: 'sociaal',
    name: 'Sociale Verbinder',
    description: 'Sterk extravert, normgericht, weinig prikkelgevoelig.',
    values: { openheid: 55, consciëntieusheid: 58, introversie: 85, normgerichtheid: 78, routinebehoefte: 55, prikkelgevoeligheid: 28, aandachtsregulatie: 65, systeemdenken: 40 },
    note: 'Didactisch composiet.',
  },
];
